### ISSUE TITLE
Implementar texturas dinámicas

### ISSUE THREAD

**Issue by francosep** [TeraCityCC4401/TeraCity#1]
Terasology usa texturas almacenadas en archivos. Esto no funciona bien por el caso de TeraCity,
que necesita generar texturas dinámicamente (e.q. para colores de metricas, outline del codigo).
Se requiere implementar texturas dinámicas, y un tipo de bloque que usa esas texturas. Esto es
base para otras extensiones.

**Comment by francosep** [comment]
Hasta el momento, la elección de textura posee cierta cantidad de imágenes con distintos anchos de línea, y el programa escoge la que 'más se asemeje' al largo de las líneas de código.
Lo que se solicita es poder calcular el largo de las líneas de código y generar una textura correspondiente a esto al cargar el programa.

**Comment by aferral** [comment]
link a la wiki del articulo https://github.com/TeraCityCC4401/TeraCity/wiki/Dynamic-Textures-%5BNOT-YET-COMPLETE%5D

**Comment by HuanRE** [comment]
http://docs.oracle.com/javase/tutorial/2d/
Tal vez la librería de gráficos 2D de Java puede ayudar a generar las imágenes del texto
