### ISSUE TITLE
Creación de ventana visual de bookmarks

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#17]
[RU](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru10---make-more-than-one-bookmark-visually-and-manage-them-with-a-list)
[Branch](https://github.com/TeraCityCC4401/TeraCity/tree/bookmarks-gui)
**Solo se cubre el ambito visual, la funcionalidad queda para otras issue.
Se debe implementar un botón en el menú de pausa, el cual lleva a una ventana con una lista de bookmarks y un botón que añade nuevos.

**Comment by NicolasBravo94** [comment]
La implementación funciona, pero las clases creadas están en el modulo equivocado ya que engine solamente implementa características de Terasology, se debe buscar una forma de copiar la implementación de Coloreo (caracteristica visual de TeraCity)

**Comment by bermann** [comment]
Las clases implementadas son AddBookmarkPopup.java y BookmarksMenuScreen.java. Ambas están en el paquete org.terasology.rendering.nui.layers.mainMenu
