### ISSUE TITLE
Listar visualmente bookmarks

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#18]
[RU](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru10---make-more-than-one-bookmark-visually-and-manage-them-with-a-list)
[Branch](https://github.com/TeraCityCC4401/TeraCity/tree/bookmarks-gui)

Se debe poder listar en la ventana de bookmarks, todos los bookmarks actuales. Según el formato

Nombre bookmark | Nombre clase

**Comment by bermann** [comment]
Ya se listan, está hecho en el commit [799f257](https://github.com/TeraCityCC4401/TeraCity/tree/799f25769aefc6f618a9a8246a56cc335453311e)

**Comment by bermann** [comment]
Ya se listan, está hecho en el commit [799f257](https://github.com/TeraCityCC4401/TeraCity/tree/799f25769aefc6f618a9a8246a56cc335453311e)
