### ISSUE TITLE
Disminuir carga de módulos innecesarios

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#19]
[RU](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru08---decrease-workload-for-unnecessary-modules)
Verificar cuales módulos cargados en la inicialización son innecesarios, y eliminarlos de esta.

**Comment by adderou** [comment]
Gran parte de los módulos no pudo ser eliminada debido a que son parte vital de la estructura del core de TeraCity.  A pesar de ello, se hizo una limpieza transversal de componentes que no aportaban en el propósito del proyecto.
