### ISSUE TITLE
Consulta de código

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#21]
[RU](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru11---code-consultation)
Poder consultar en una ventana aparte el código de un bloque.
Revisar esto ya que al parecer se encuentra implementado.

**Comment by fcopulgar** [comment]
Se agrega una GUI para poder leer y editar el código que representa cada edificio dentro del mismo Minecraft.

**Comment by fcopulgar** [comment]
Se agrega un color diferente a los comentarios.
