### ISSUE TITLE
Edición de comentarios

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#22]
[RU](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru12---showedit-code-comments)
Se debe poder editar solamente los comentarios del codigo fuente.

**Comment by fcopulgar** [comment]
La creación de menús es estática y se necesita a priori saber cuatos campos de texto van haber para poder setearlos. Para pode editar solo comentarios habría que poner "x" cantidad de campos de texto no editable y "y" campos de texto editable, donde "x" es la cantidad de comentarios e "y" la cantidad de código editable. Como el atributo de edición y el campo en si mismo van en el archivo *.ui no podemos agregar dinámicamente diferentes cantidades de textBoxs según cantidad de cometarios y código editable.
