### ISSUE TITLE
Agregar bookmark

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#23]
[RU](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru10---make-more-than-one-bookmark-visually-and-manage-them-with-a-list)
Se debe poder agregar bookmarks por medio de la gui de bookmarks creada en #17.
Se debe ingregar el nombre de la clase y el nombre de su bookmark y apretar un botoón para agregarlo.
Se abrir la ventana de agregado debe aparecer en el campo de nombre de clase la clase objetivo actual (centro de la pantalla) como sugerencia.

**Comment by bermann** [comment]
Está hecho en el commit [4bc044e](https://github.com/TeraCityCC4401/TeraCity/commit/4bc044ef0208cab166eb3a9973e554462b800d90)
