### ISSUE TITLE
Crear bloque especial que utilice texturas dinamicas

### ISSUE THREAD

**Issue by aferral** [TeraCityCC4401/TeraCity#24]
Requisito de Software asociado a [RU01](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru01---dynamic-textures)
Todos los bloques hasta el momento utilizan texturas que se encuentran en archivos. El objetivo ahora es extender los bloques para soportar imagenes que se generen dinamicamente.

**Comment by aferral** [comment]
Concept location: Comenzare por buscar dos conceptos el primero la creacion de un bloque nuevo. El segundo la vinculacion de un bloque con su TileData correspondiente (para mas detalles sobre Assets, tile data ver [link wiki](https://github.com/TeraCityCC4401/TeraCity/wiki/Dynamic-Textures-%5BNOT-YET-COMPLETE%5D))

**Comment by aferral** [comment]
La creacion de bloques es bastante facil el proceso se detalla en https://github.com/TeraCityCC4401/TeraCity/wiki/Block-architecture .  Cree un bloque de prueba para verificar si puedo hacer cambiar su textura en tiempo de ejecucion. Queda por localizar vinculacion TileData block.

**Comment by aferral** [comment]
Concepto localizado en WorldAtlas. Esta clase manjea que Tile_data se asocia a cada AssetUri de tipo Block_tile. Ademas posee un diccionario AssetUri -> Tile_data. Creo que si logro modificar este diccionario cambiaran las texturas en tiempo de ejecucion (no estoy del todo seguro ya que la interfaz no muestra funciones que retornen esta tile_data)

**Comment by aferral** [comment]
Intente realizar dicho proceso, pero el sistema tiene alguna clase de sandboxs para los modulos. Es decir no puedo llegar e ir a buscar el WorldAtlas que se encuentra en el core. Esto presupone dos cosas O quitamos la seguridad ? O nos ajustamos a la API para mods? Mas detalles de todo este proceso en https://github.com/TeraCityCC4401/TeraCity/wiki/Where-to-place-the-dynamic-block-%3F

**Comment by aferral** [comment]
Cambie el enfoque a buscar la forma de crear bloques en tiempo de ejecucion seteando una configuracion arbitraria. Este enfoque dio frutos por el momento se testeo asignando varias texturas ya cargadas a un bloque generado dinamicamente. Queda ver asignar ahora texturas dinamicamente creadas.

**Comment by HuanRE** [comment]
Los permisos están en un archivo que se encuentra al causar el error

**Comment by HuanRE** [comment]
Usando temporalmente una clase con todos los privilegios (AssetManagerImpl), se logra crear un TileData con la imagen pero no se logra inscribir este nuevo asset (el generarlo retorna null).

**Comment by aferral** [comment]
Con los nuevos cambios es posible crear un bloque y asignarle a cada cara un BLOCK_TILE ya registrado (AssetUri). Respecto a la creacion del bloque en tiempo de ejecucion eso esta resuelto. Al menos en terminos de concepto, queda analizar impacto, formular una solucion algo mas ordenada (refactorizar)  y testear.

 El problema ahora esta en registrar una textura, el problema resulto no ser trivial y se abrira otra issue.

**Comment by aferral** [comment]
https://github.com/TeraCityCC4401/TeraCity/commit/657f140f521220c1e142195bb038f2ef9cf3eaa5

**Comment by NicolasBravo94** [comment]
RU no realista

**Comment by HuanRE** [comment]
No es posible tener un bloque que use una textura generada dinámicamente, ver comentarios de cierre de #31 y #29
