### ISSUE TITLE
Permitir ancho variable de edificios

### ISSUE THREAD

**Issue by francosep** [TeraCityCC4401/TeraCity#25]
Requisito de Software asociado a [RU02](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru02---variable-width-for-buildings)
Modificar el módulo de carga de edificios para que permita la generación de los mismos con una cantidad variable de cubos.

**Comment by francosep** [comment]
Por ahora, se trabajará en crear un ancho distinto fijo para determinar el punto en el cual el programa establece el ancho de los edificios.

**Comment by francosep** [comment]
Se suma @adderou

**Comment by francosep** [comment]
Anotaciones:

- DrawableCodePackage es la representación del dibujo de un package en el juego (Base), la cual posee una lista de subpackages y clases en contentList.
- CodePackage almacena dicha info y acepta visitors
- CodeCityProjectLoader: Clase clave. Revice el path del proyecto a representar, además de enviar a CodePackage los paquetes y clases, diferenciando los unos de los otros comprobando si el path entregado es una carpeta o no; de serlo se considera package y se genera recursión dentro de la misma, de no serlo se considera clase y se genera un new CodeClass indicando el nombre y diversas métricas.

**Comment by francosep** [comment]
El ancho del edificio se determina con `return scale.getScaledSize(base.getVariableNumber(), 1);`.
La función `scale.getScaledSize(a, b);` retorna el máximo entre a/2 y b, y `base.getVariableNumber()`, función que se encuentra en CodeClass, retorna el número de variables de una clase.
Dado que este valor se indica como 0 en CodeCityProjectLoader (Además de un flag TODO), la función retornará 0, haciendo que la función `scale.getScaledSize(a, b);` retorne siempre 1.

**Comment by francosep** [comment]
CodeCityProjectLoader, al parecer, no es la única parte en donde crea instancias de CodeClass: Es posible notar que igualmente crea edificios de 2x2.
Para comprobar esto, se imprimió la variable 'Variable' de CodeClass, encontrándose con casos en donde dicho valor es distinto de 0.

**Comment by francosep** [comment]
Cuando no se ingresa un path o este es incorrecto, se carga la clase CodeCityDefaultLoader, la cual genera una serie de objetos CodeClass, cuyo valor de variables varía entre

**Comment by adderou** [comment]
Se utilizará inicialmente el tamaaño de la línea más larga de código para determinar el ancho de los edificios. Para ello, el ancho será proporcional a la raíz cuadrada del largo en caracteres de la línea más larga.

**Comment by adderou** [comment]
Para realizar el análisis posterior con el número de variables, se buscará una forma de interpretar el código completo, de tal modo de encontrar facilmente los valores de algunas métricas utilizadas.

**Comment by adderou** [comment]
Se descubre que la escala horizontal y vertical en el código son manejadas en espacios distintos. Por lo tanto, en estos momentos la escala de líneas de código es lineal con constante proporcional 0,5, y la de línea más larga es proporcional a su raíz cuadrada.

**Comment by adderou** [comment]
Hay un problema al manejar los tamaños del ancho con las plataformas (Paquetes). Éstos no se ajustan correctamente a la escala escogida, es necesario corregi resto.

**Comment by adderou** [comment]
Ancho variable de edificios completado. Queda definir métricas para usar este ancho variable.
