### ISSUE TITLE
Creación GUI para consultar código de clase objetivo

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#28]
Se necesita crear un panel dentro del juego que muestre el texto del código de una clase objetivo, esta GUI debe recibir un string (código java) y mostrarla en un panel. Además debe tener un botón para cerrar este panel.

**Comment by fcopulgar** [comment]
Se crea una GUI para ver y editar el código de un edificio dentro del mismo Minecraft.
