### ISSUE TITLE
Renderizar texturas generadas dinamicamente

### ISSUE THREAD

**Issue by aferral** [TeraCityCC4401/TeraCity#29]
En continuacion con el requisito ( #24 ) se requiere que las texturas sean aceptadas por el render. Hasta el momento estan inscritas en AssetManager sin embargo no aparecen en el render. Buscando en el codigo, la parte donde maneja las texturas de bloque se llama WorldAtlas la cual en un inicio del juego toma todas las texturas registradas y arma una imagen gigante con todas estas. Luego se hace el render tomando trozos de esta imagen gigante (esto ni idea donde es). EL problema resulta de que al agregar una nueva textura tendriamos que generar denuevo este worldatlas  Lo cual hasta el momento no resulta.

**Comment by HuanRE** [comment]
Intentar generar el atlas nuevamente genera un error de falta de contexto de OpenGL

**Comment by HuanRE** [comment]
Comentario: buscando "Coloring" en engine encontré la clase ModuleManager que parece manejar los permisos.

**Comment by NicolasBravo94** [comment]
La clase AbstractAssert tiene el método reload(data). Podría ser posible ocuparlo para recargar el assert de textura de un bloque con datos nuevos.

**Comment by NicolasBravo94** [comment]
La API Assets.class entrega el método generateAsset(data, assetClass) el cual permite crear assets (recursos) de manera temporal.

**Comment by NicolasBravo94** [comment]
ComputerMonitors para crear una textura utiliza:
`        Texture texture = Assets.generateAsset(new TextureData(width, height, new ByteBuffer[]{resultBuffer}, Texture.WrapMode.REPEAT, Texture.FilterMode.NEAREST), Texture.class);
`
pero por alguna razón esta linea no funciona con el proyecto. Se debe adaptar si se desea ocupar.

**Comment by NicolasBravo94** [comment]
Cambio de planificación:
Se procederá a implementar solución con Atlas modificado, y asignar nueva textura como el procedimiento de highlight de search

**Comment by NicolasBravo94** [comment]
RU no realista

**Comment by HuanRE** [comment]
Al intentar usar el engine actualizado, ocurrieron lo siguientes problemas:
- Intentar pasar TeraCity al engine nuevo implicaría reimplementar todo el trabajo de los últimos semestres de TeraCity ya que la API del engine cambió y algunos cambios agregaron cosas al engine antiguo.
- Intentar localizar el área específica del engine que implementa los computer monitor se encuentra que se modificó toda la estructura del engine con generics, por lo que también habría que refactorizar todo elemento que usa esto, cambiando la API del engine y llegando al mismo problema anterior.
