### ISSUE TITLE
Generar imágenes de bloques con mayor resolución

### ISSUE THREAD

**Issue by HuanRE** [TeraCityCC4401/TeraCity#30]
Hay que modificar el factory para que acepte mejor resolución y cantidades distintas a dos líneas de código por línea

**Comment by HuanRE** [comment]
Concept Location: Generar las imágenes está en BlockTextureFactory, eso es lo que hay que modificar

**Comment by HuanRE** [comment]
Análisis de impacto: Por ahora nada ya que nada todavía usa la BTF

**Comment by HuanRE** [comment]
Cambio de planes: Ahora las texturas se cargarán desde archivos, y representarán dos caracteres en dos líneas

**Comment by aferral** [comment]
Nueva descripción del requisito: Se debe implementar una visualización del código mas representativa que las actuales. Para esto se va realizar una version de baja resolución del código entero con pixeles de 2x2 que se repartirán posteriormente en las caras de los edificios.

**Comment by aferral** [comment]
Concept Location: Los conceptos mas importantes son la creacion de caras de edificios y codigo. Debido a que ya  se trabajo con estos conceptos en requisitos anteriores se localizan todos estos conceptos en el modulo WorldCodeCity

**Comment by aferral** [comment]
Impact analisis. Una inspeccion mas detallada del codigo muestra que en CodeCityBuildingRasterizer seria el lugar indicado para colocar una fabrica que dada la matriz binaria ajustara el bloque necesario.
Es necesario obtener informacion row,col en esta representacion a partir de los bloques. Para esto se utilizo una extension del MapObject con variables maxHeightCord, Column (con estas variables y las cordenadas del bloque a colocar se inducen row,column).

**Comment by aferral** [comment]
Estrategia propuesta 
	-En la generacion de CodeObject tomar la lectura de archivo y calcular ahi representacion binaria
	-Agregar nueva variable int[][] que guarde matriz representativa private int[][] binaryRepresentation;
	-Aditar interfaz DrawableCode para conseguir esta (DrawableCode contiene CodeObject)
	-Conseguir esta estructura  
        -Calcular Row,Column para objener seccion de bloque correspondiente

**Comment by aferral** [comment]
Pre factoring
Buscando en el codigo resulta que no se cargaban los archivos realmente sin un path. El caso por defecto corresponde a armar objetos Dummy. Se cambio esto para mantener todos los casos en una misma interface de carga.
Se extienden variables mapObject para soportar guardar maxHeightCord, Column
Se extiende interface Drawable object para acceder a la representacion binaria.

**Comment by aferral** [comment]
Actualizacion:
Se agrego en clases CodeCityBuildingProvider, CodeMapHash casos para ajustar las variables MapObject 
Se encontro que se debian colocar bloques de bordes para evitar que dos bloques tuviesen mas de una textura. Este cambio aparece en CodeMapHash tambien.

**Comment by aferral** [comment]
Post refactoring
             Quedaron algunas variables de metodos antiguos ya obsoletos, pero se postergara el post refactoring hasta tener la factory de int[][] a Block para evitar posibles conflictos.

**Comment by aferral** [comment]
Verificacion y testeo.
Pequeño test con clase de prueba y verificación manual.

**Comment by aferral** [comment]
Todo lo anteriormente mencionado incluido en https://github.com/TeraCityCC4401/TeraCity/commit/cfb883d551332fa863171e8432c55cb59cef2446

**Comment by aferral** [comment]
Arreglado algunos bugs que el edificio quedaba espejado en algunas caras, se mostraba mal algunas caras.
https://github.com/TeraCityCC4401/TeraCity/commit/ce4c15d4eb3fe73f5bba209977ef416f944ac44a

**Comment by aferral** [comment]
Arreglado un bug de bordes desfasados en una esquina
https://github.com/TeraCityCC4401/TeraCity/commit/06fd60faca640550201fa456f4d3fecd7c965cef
Se tiene funcionalidad deseada se cierra el issue.
