### ISSUE TITLE
Agregar textura dinámica al Atlas

### ISSUE THREAD

**Issue by NicolasBravo94** [TeraCityCC4401/TeraCity#31]
Se debe poder insertar una nueva textura en tiempo de ejeución en el Atlas sin la necesidad de recargarlo y por lo tanto sin recargar el mundo completamente. Requisito necesario para #29.

**Comment by aferral** [comment]
Concept Location:
En una busqueda inicial se encuentra en WorldAtlasImpl el concepto de atlas, AssetManager la administracion de recursos como texturas, 

Impact analysis: 
Despues de una busqueda algo mas profunda el cambio esta altamente deslocalizado, no se logro ubicar la conexion entre Block_Tiles y el render. Se logro ubicar una conexion entre texturas y el render en OpenGLTexture. En esta clase se logro remplazar las texturas por array de bytes (cuando iniciaba el mapa), pero no se logro utilizar esta funcion en un tiempo posterior (tiempo de ejecucion como se requiere)

Varios intentos se realizaron para lograr el objetivo, pero el problema sigue siendo ubicar la textura en el render. De hecho se requiere crear un nuevo tipo de textura, las texturas que existen hasta el momento son dos headLessTexture (para pruebas) y OpenGLTextura siendo la ultima imposible de utilizar fuera de un contexto de OpenGL. Respecto al atlas se logro conseguir este en tiempo de ejecucion, se logro cargar las imagenes en tiempo de ejecucion, pero se ve bastante dificil lograr agregar las block_tile.

**Comment by NicolasBravo94** [comment]
RU no realista

**Comment by HuanRE** [comment]
El atlas se destruye al iniciar el programa por lo que para agregar texturas a éste habría que reiniciar el juego cada vez que se quiera agregar una textura
