### ISSUE TITLE
Generar AST del código

### ISSUE THREAD

**Issue by adderou** [TeraCityCC4401/TeraCity#33]
Se necesita crear un AST de cada clase analizada para poder obtener facilmente las métricas del código, tales como número de métodos, de propiedades, largo de clase o tamaño promedio de las líneas.
Requisito: [RU05](https://github.com/TeraCityCC4401/TeraCity/wiki/Requirements#ru05---extend-metrics-to-buildings)

**Comment by francosep** [comment]
Concept location: Al buscar los términos "Class" y "path" se reconoce la clase CodeClass que contiene la información necesaria para acceder a los archivos de clase

**Comment by francosep** [comment]
Análisis de impacto: Se modificará CodeClass para añadir un nuevo campo que almacene el AST. Dado esto, sólo se verá afectada esta clase (Por ahora)

**Comment by francosep** [comment]
Se pretende añadir funciones externas que permitan obtener el AST. Hasta ahora se han visto las siguientes opciones:
- javaparser
- jexast
Aun así, cabe considerar que ambos se basan en una función que se encuentra en org.eclipse.jdt (Java Development Tools)

**Comment by francosep** [comment]
Finalmente se utlizará la herramienta [javaparser](https://github.com/javaparser/javaparser) dada su versatilidad y gran cantidad de formas de uso.

**Comment by francosep** [comment]
Para poder utilizar las funcionalidades añadidas, se requiere refrescar el proyecto WorldCodeCity, para que así Eclipse descargue los imports realizados

**Comment by francosep** [comment]
Se trabajará en branch RU05_AST

**Comment by burningreds** [comment]
Importaciones fallan al incluir el módulo en el proyecto completo. Se reabre el issue.

**Comment by NicolasBravo94** [comment]
Importación de librería exitosa, ahora CodeClass tiene tu propio AST al cual se puede tener acceso. 
Adicionalmente se mejoró CodeCityProjectLoader para leer solo 2 veces cada archivo en vez de 4.

**Comment by NicolasBravo94** [comment]
Mergeado
