### ISSUE TITLE
Crear GUI para visualización de métricas de código

### ISSUE THREAD

**Issue by francosep** [TeraCityCC4401/TeraCity#41]
Se requiere una forma para poder visualizar las métricas del código apuntado por el jugador. Por ahora, se manejan 3 opciones:

- Generar cuadro flotante en pantalla que lo muestre.
- Mostrar en pantalla completa las métricas (Similar a lo ocurrido con "Edit Class").
- Mostrar en consola.

**Comment by francosep** [comment]
Branch: [AST_Overlay](https://github.com/TeraCityCC4401/TeraCity/tree/AST_Overlay)

**Comment by francosep** [comment]
Concept location:

- org.terasology.logic.players.DebugControlSystem#onKeyDown posee binding el pulsar F3, el cual muestra en pantalla el debug, la cual es la presentación buscada
- org.terasology.logic.chat contiene la lógica para tratar los mensajes de chat

**Comment by francosep** [comment]
org.terasology.logic.chat.ChatSystem contiene la UI

**Comment by adderou** [comment]
org.terasology.logic.chat.ChatSystem contiene el objeto

**Comment by adderou** [comment]
Después de conversación con el cliente, se define que las métricas deberán mostrarse tanto en overlay como en la pantalla de edición de código.

**Comment by adderou** [comment]
En la pantalla de edición de código se mostrará además la posibilidad de hacer "blame" de algunas líneas de texto.

**Comment by adderou** [comment]
Finalmente, para el overlay se utilizará el código de Debug, el cual se encuentra en _engine/src/main/resources/assets/ui/ingame/debugOverlay.ui_ (Interfaz) y _TeraCity/modules/jeditint/src/main/java/org/terasology/rendering/nui/layers/ingame/EditClassScreen.java_ (Código)
Para mostrar las métricas en la pantalla de edición de código, se modificará el archivo _engine/src/main/resources/assets/ui/ingame/editClassScreen.ui_ (Interfaz) y _/home/adderou/Projects/Java/TeraCity/modules/jeditint/src/main/java/org/terasology/rendering/nui/layers/ingame/debugOverlay.java_(Código)

**Comment by adderou** [comment]
Requisito completo, utilizando las clases mencionadas anteriormente.
