### ISSUE TITLE
Permitir múltiples bookmarks y generar lista de ellos

### ISSUE THREAD

**Issue by francosep** [TeraCityCC4401/TeraCity#9]
Se puede hacer mas de un “bookmark” en la visualizacion, y se puede manejar la lista de los
bookmarks.

**Comment by francosep** [comment]
Bookmark: Guarda la posición y orientación de algún punto dentro del juego y permite teletransportarse a éste.

**Comment by NicolasBravo94** [comment]
Añadir un bookmark y listar bookmarks ya está implementado como instrucción de consola:

Para añadir un bookmark:
addBookmark <className> <bookName>

Para listar todos los bookmarks:
diplayBookmarks

ambos métodos son de la clase FlyMode/src/main/java/searchMode/SearchCommands.java

**Comment by NicolasBravo94** [comment]
Los bookmarks se manejan con 2 hashmap:
- "bookMarks" asocia el nombre del bookmark a la posición espacial del edificio de la clase
- "bookMarksName" asocia el nombre dle bookmark con en nombre de la clase

**Comment by bermann** [comment]
Se añadió botón de Bookmarks en menú de pausa. Por ahora no tiene funcionalidad.

Para hacerlo se modificaron los siguientes archivos:
1. engine/src/main/resources/assets/ui/ingame/pauseMenu.ui
2. engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java
